### PR TITLE
replace overbroad except clauses with if statement and stop shadowing…

### PR DESCRIPTION
**Pull request by Eh2406**
most of a fix for #3

### CODE REVIEW

**Comment by smmaurer** [comment]
This looks great, thank you!

Can you also add an update to the documentation in `README.md` to reflect the change in argument names from max -> maximum and min -> minimum?

(For my own benefit, is there a general principle for that? Is it just that the full word is clearer?)

**Comment by Eh2406** [comment]
No it is that `min` is a built in function of python. So it is easy to make mistakes. if we had

```
(column_name, str(min(ds)), str(min))
```

It would have been wrong. Pycharm yelled at me. Doc fix incoming.

**Comment by smmaurer** [comment]
Ah, makes sense. Thanks!

**Comment by Eh2406** [comment]
Do you have advice for the TODO's?

**Comment by smmaurer** [comment]
About logging the backtraces? No, i'm not sure how we should handle that. 

One of the things i haven't gotten around to is adding Python 3 cross-compatibility, which might give us better options. (I'll open a new issue for that.)

**Comment by Eh2406** [comment]
Or we can use the `try` but specify the error types we expect. What error do we expect from orca?

**Comment by smmaurer** [comment]
I don't know. It could be pretty much anything, because Orca will execute whatever arbitrary code is in the table definition in order to generate it. Seems like ideally we should raise an OrcaAssertionError but also provide the backtrace that triggered it, if possible?

**Pull request merged**
